### ISSUE TITLE
Readme missing some usage steps

### ISSUE THREAD

**Issue by Macrofig** [canjs/steal-stache#23]
I attempted to add this plugin to my project using only the readme documentation as a guide. I was unaware that the project's package.json needed modification.

Add quick note about adding to system.plugins.

**Comment by leoj3n** [comment]
I think it's now `steal.plugins` the modification you would need to do in `package.json`.

Like documented here:

http://stealjs.com/docs/steal-css.html

**Comment by justinbmeyer** [comment]
It should be documented here: http://canjs.com/doc/steal-stache.html

And the readme should probably point to that.

**Comment by chasenlehara** [comment]
We’ve updated the docs here: https://canjs.com/doc/steal-stache.html#Use

…and the README now points to that 😊
