### ISSUE TITLE
Object passed to renderer is no longer used as the template’s helpers

### ISSUE THREAD

**Issue by chasenlehara** [canjs/steal-stache#65]
Previously, code like this:

```js
import template from "template.stache!steal-stache";
template({}, {
  myHelper: () => { }
})
```

…would result in `myHelper` being available in the template because of this code in `can-stache`: https://github.com/canjs/can-stache/blob/89a49e8fa7fb53e790626273822356e82f0022df/src/html_section.js#L51-L56

`steal-stache` was recently changed from basically passing the second `options` argument straight to `can-stache`: https://github.com/canjs/steal-stache/blob/9dfd0573be0cc1ff6a0fdd40e271bae34d226ae8/steal-stache.js#L17-L18

…to checking for `helpers` specifically in the `options`: https://github.com/canjs/steal-stache/blob/769e7d6e1794bc22e1fcbd7f22bb19b7b87011b2/steal-stache.js#L17-L18

I think this is a regression but I’m not 100% sure; I understand the [steal-stache docs](https://canjs.com/doc/steal-stache.html#STACHE_MODULE_NAME_steal_stache) to say that the second argument you pass is the helpers object.

**Comment by justinbmeyer** [comment]
cc @matthewp

**Comment by matthewp** [comment]
Yeah it's a regression. It was attempting to fix a bug where module wasn't being passed through, sounds like maybe it is overwriting passed in helpers.

**Comment by matthewp** [comment]
Fixed in https://github.com/canjs/steal-stache/releases/tag/v4.1.2
