### ISSUE TITLE
Plz move repo over to Matthue http://github.com/stealjs

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/steal-stache#7]
I think this repo is in the wrong org greetings

**Comment by matthewp** [comment]
It could really go in either org, canjs is as good of a choice as stealjs.

**Comment by frank-dspeed** [comment]
not realy its using steal its steal dependent its a total mix up i need this all clean :)

**Comment by matthewp** [comment]
It depends on both stealjs and canjs, I believe it belongs more in canjs since it's a a Steal plugin for canjs. The same way if we had a webpack plugin it would belong in the canjs org and not in webpack's org (or a RequireJS plugin would not belong in requirejs' org). It's a canjs project.

**Comment by frank-dspeed** [comment]
double checked

in your usage and info its clear too its realy a steal plugin that allows to read that syntax and load it sorry i say move it to steal as it does use steal to load canjs canjs is not using steal to load anything ok a component maybe does but the module loader neads steal and this interacts directly with the steal object 

```
Usage

This package will configure Steal so that you can import templates. Start by installing with NPM.

npm install steal-stache --save
And then assuming you are using NPM with Steal like:

<script src="node_modules/steal/steal.js"></script>
All you have to do is import the template:

import template from "./main.stache";
steal-stache Object
STACHE_MODULE_NAME!steal-stache
API

steal-stache Object

A StealJS extension that allows stache templates as dependencies.
```

**Comment by frank-dspeed** [comment]
steal-stache Object

A StealJS extension that allows stache templates as dependencies.

**Comment by justinbmeyer** [comment]
Closing as I consider this the CanJS's project's responsibility to maintain.  

The technical considerations you bring up are why it's called `steal-stache` not `stache-steal`.  But those technical considerations are unimportant in terms of the responsibility to maintain this project.
