### ISSUE TITLE
IE11 Object.assign error

### ISSUE THREAD

**Issue by mitch-mitchel** [canjs/steal-stache#81]
Steal-stache 4.1.x does not seem to support IE11 as I need to manually polyfill `Object.assign`. The error that throws is at this return statement:

https://github.com/canjs/steal-stache/blob/15fecaceefc80b1a605baee4798ba314e0e8dfba/steal-stache.js#L11

My app is currently using 4.1.2 as a dependency from these packages:
<img width="525" alt="Screen Shot 2019-06-29 at 9 48 28 AM" src="https://user-images.githubusercontent.com/11528248/60385826-853f6c00-9a53-11e9-8a8f-2395fea77e5e.png">

**Comment by justinbmeyer** [comment]
The easy fix to this is to add `can-assign` to the imports and then use that.

**Comment by chasenlehara** [comment]
@mikemitchel Should this have been closed by https://github.com/canjs/steal-stache/pull/82?

**Comment by matthewp** [comment]
Yeah, it should.
